target:
  host: ghcr.io
  repository: stackhpc
  auth:
    username: GHCR_USERNAME
    password: GHCR_PASSWORD
sources:
- repository: calico/cni
  tag: v3.21.2
- repository: calico/kube-controllers
  tag: v3.21.2
- repository: calico/node
  tag: v3.21.2
- repository: calico/pod2daemon-flexvol
  tag: v3.21.2
- repository: rancher/hyperkube
  tag: v1.21.9-rancher1
  target_tag: v1.21.9 
