target:
  host: ghcr.io
  repository: stackhpc
  auth:
    username: GHCR_USERNAME
    password: GHCR_PASSWORD
sources:
# Calico
# v3.21.2
- repository: calico/cni
  tag: v3.21.2
- repository: calico/kube-controllers
  tag: v3.21.2
- repository: calico/node
  tag: v3.21.2
- repository: calico/pod2daemon-flexvol
  tag: v3.21.2
# v3.21.4
- repository: calico/cni
  tag: v3.21.4
- repository: calico/kube-controllers
  tag: v3.21.4
- repository: calico/node
  tag: v3.21.4
- repository: calico/pod2daemon-flexvol
  tag: v3.21.4
# v3.26.3
- repository: calico/cni
  host: docker.io
  tag: v3.26.3
- repository: calico/kube-controllers
  host: docker.io
  tag: v3.26.3
- repository: calico/node
  host: docker.io
  tag: v3.26.3
- repository: calico/pod2daemon-flexvol
  host: docker.io
  tag: v3.26.3
# v3.27.0
- repository: calico/cni
  host: docker.io
  tag: v3.27.0
- repository: calico/kube-controllers
  host: docker.io
  tag: v3.27.0
- repository: calico/node
  host: docker.io
  tag: v3.27.0
- repository: calico/pod2daemon-flexvol
  host: docker.io
  tag: v3.27.0

# Conformance
- repository: conformance
  host: registry.k8s.io
  tag: v1.23.6

# CoreDNS
- repository: coredns/coredns
  host: docker.io
  tag: 1.8.7
- repository: coredns/coredns
  host: docker.io
  tag: 1.9.4
- repository: coredns/coredns
  host: docker.io
  tag: 1.10.0
- repository: coredns/coredns
  host: docker.io
  tag: 1.11.1

# etcd
- repository: coreos/etcd
  host: quay.io
  tag: v3.4.18
- repository: coreos/etcd
  host: quay.io
  tag: v3.5.4
- repository: coreos/etcd
  host: quay.io
  tag: v3.5.10

# Grafana
- repository: grafana/grafana
  tag: 8.3.6
- repository: grafana/grafana
  host: docker.io
  tag: 10.2.0

# ingress-nginx
- repository: ingress-nginx/kube-webhook-certgen
  host: k8s.gcr.io
  tag: v1.1.1
- repository: ingress-nginx/controller
  host: k8s.gcr.io
  tag: v1.1.2

# k8scloudprovider
# OCCM
- repository: k8scloudprovider/openstack-cloud-controller-manager
  tag: v1.23.1
- repository: provider-os/openstack-cloud-controller-manager
  host: registry.k8s.io
  tag: v1.27.3
- repository: provider-os/openstack-cloud-controller-manager
  host: registry.k8s.io
  tag: v1.28.1
# barbican-kms-plugin
- repository: k8scloudprovider/barbican-kms-plugin
  tag: v1.23.0
- repository: provider-os/barbican-kms-plugin
  host: registry.k8s.io
  tag: v1.27.3
- repository: provider-os/barbican-kms-plugin
  host: registry.k8s.io
  tag: v1.28.1
# cinder-csi-plugin
- repository: k8scloudprovider/cinder-csi-plugin
  tag: v1.23.0
- repository: provider-os/cinder-csi-plugin
  host: registry.k8s.io
  tag: v1.27.3
- repository: provider-os/cinder-csi-plugin
  host: registry.k8s.io
  tag: v1.28.1
# k8s-keystone-auth
- repository: k8scloudprovider/k8s-keystone-auth
  tag: v1.23.0
- repository: provider-os/k8s-keystone-auth
  host: registry.k8s.io
  tag: v1.27.3
- repository: provider-os/k8s-keystone-auth
  host: registry.k8s.io
  tag: v1.28.1
# magnum-auto-healer
- repository: k8scloudprovider/magnum-auto-healer
  tag: v1.23.0
- repository: provider-os/magnum-auto-healer
  host: registry.k8s.io
  tag: v1.27.3
- repository: provider-os/magnum-auto-healer
  host: registry.k8s.io
  tag: v1.28.1
# manila-csi-plugin
- repository: k8scloudprovider/manila-csi-plugin
  tag: v1.23.0
- repository: provider-os/manila-csi-plugin
  host: registry.k8s.io
  tag: v1.27.3
- repository: provider-os/manila-csi-plugin
  host: registry.k8s.io
  tag: v1.28.1
# octavia-ingress-controller
- repository: k8scloudprovider/octavia-ingress-controller
  tag: v1.23.0
- repository: provider-os/octavia-ingress-controller
  host: registry.k8s.io
  tag: v1.27.3
- repository: provider-os/octavia-ingress-controller
  host: registry.k8s.io
  tag: v1.28.1

# k8s-sidecar
- repository: kiwigrid/k8s-sidecar
  host: quay.io
  tag: 1.15.6

# metrics-server
- repository: metrics-server/metrics-server
  host: k8s.gcr.io
  tag: v0.5.2

# openstackmagnum/cluster-autoscaler
- repository: openstackmagnum/cluster-autoscaler
  tag: v1.22.0
- repository: openstackmagnum/cluster-autoscaler
  tag: v1.23.0
- repository: openstackmagnum/cluster-autoscaler
  tag: v1.27.3

# Prometheus
- repository: prometheus/alertmanager
  host: quay.io
  tag: v0.23.0
- repository: prometheus/prometheus
  host: quay.io
  tag: v2.33.4
- repository: prometheus-adapter/prometheus-adapter
  host: k8s.gcr.io
  tag: v0.9.1
- repository: prometheus-operator/prometheus-operator
  host: quay.io
  tag: v0.54.1

# Rancher Hyperkube
- repository: rancher/hyperkube
  tag: v1.21.9-rancher1
  target_tag: v1.21.9 
- repository: rancher/hyperkube
  tag: v1.22.6-rancher1
  target_tag: v1.22.6
- repository: rancher/hyperkube
  tag: v1.23.4-rancher1
  target_tag: v1.23.4
- repository: rancher/hyperkube
  tag: v1.23.5-rancher1
  target_tag: v1.23.5
- repository: rancher/hyperkube
  tag: v1.23.6-rancher1
  target_tag: v1.23.6
- repository: rancher/hyperkube
  tag: v1.23.15-rancher1
  target_tag: v1.23.15
- repository: rancher/hyperkube
  tag: v1.24.16-rancher1
  target_tag: v1.24.16
- repository: rancher/hyperkube
  tag: v1.25.12-rancher1
  target_tag: v1.25.12
- repository: rancher/hyperkube
  tag: v1.26.7-rancher1
  target_tag: v1.26.7
- repository: rancher/hyperkube
  tag: v1.27.5-rancher1
  target_tag: v1.27.5
- repository: rancher/hyperkube
  host: docker.io
  tag: v1.27.6-rancher1
  target_tag: v1.27.6
- repository: rancher/hyperkube
  host: docker.io
  tag: v1.27.8-rancher2
  target_tag: v1.27.8
# Gardener Hyperkube
- repository: gardener-project/hyperkube
  host: eu.gcr.io
  tag: v1.28.5
- repository: gardener-project/hyperkube
  host: eu.gcr.io
  tag: v1.29.0

# Thanos
- repository: thanos/thanos
  host: quay.io
  tag: v0.24.0

# K8S SIG Storage/Cinder CSI
- repository: sig-storage/livenessprobe
  host: k8s.gcr.io
  tag: v2.5.0
- repository: sig-storage/csi-node-driver-registrar
  host: k8s.gcr.io
  tag: v2.4.0
- repository: sig-storage/csi-snapshotter
  host: k8s.gcr.io
  tag: v4.2.1
- repository: sig-storage/csi-resizer
  host: k8s.gcr.io
  tag: v1.3.0
- repository: sig-storage/csi-attacher
  host: k8s.gcr.io
  tag: v3.3.0
- repository: sig-storage/csi-provisioner
  host: k8s.gcr.io
  tag: v3.0.0
