target:
  host: ghcr.io
  repository: stackhpc
  auth:
    username: GHCR_USERNAME
    password: GHCR_PASSWORD
sources:
- repository: calico/cni
  tag: v3.21.2
- repository: calico/kube-controllers
  tag: v3.21.2
- repository: calico/node
  tag: v3.21.2
- repository: calico/pod2daemon-flexvol
  tag: v3.21.2
- repository: openstackmagnum/cluster-autoscaler
  tag: v1.22.0
- repository: openstackmagnum/cluster-autoscaler
  tag: v1.23.0
- repository: rancher/hyperkube
  tag: v1.21.9-rancher1
  target_tag: v1.21.9 
- repository: rancher/hyperkube
  tag: v1.22.6-rancher1
  target_tag: v1.22.6
- repository: rancher/hyperkube
  tag: v1.23.4-rancher1
  target_tag: v1.23.4
- repository: ingress-nginx/kube-webhook-certgen
  host: k8s.gcr.io
  tag: v1.1.1
- repository: prometheus-adapter/prometheus-adapter
  host: k8s.gcr.io
  tag: v0.9.1
- repository: metrics-server/metrics-server
  host: k8s.gcr.io
  tag: v0.5.2
- repository: prometheus-operator/prometheus-operator
  host: quay.io
  tag: v0.54.1
- repository: kiwigrid/k8s-sidecar
  host: quay.io
  tag: 1.15.6
- repository: grafana/grafana
  tag: 8.3.6
- repository: prometheus/prometheus
  host: quay.io
  tag: v2.33.4
- repository: prometheus/alertmanager
  host: quay.io
  tag: v0.23.0
