target:
  host: ghcr.io
  repository: stackhpc
  auth:
    username: GHCR_USERNAME
    password: GHCR_PASSWORD
sources:
# Calico
- repository: calico/cni
  tag: v3.21.2
- repository: calico/kube-controllers
  tag: v3.21.2
- repository: calico/node
  tag: v3.21.2
- repository: calico/pod2daemon-flexvol
  tag: v3.21.2

# CoreDNS
- repository: coredns/coredns
  host: docker.io
  tag: 1.8.7

# Grafana
- repository: grafana/grafana
  tag: 8.3.6

# ingress-nginx
- repository: ingress-nginx/kube-webhook-certgen
  host: k8s.gcr.io
  tag: v1.1.1
- repository: ingress-nginx/controller
  host: k8s.gcr.io
  tag: v1.1.2

# k8scloudprovider
- repository: k8scloudprovider/openstack-cloud-controller-manager
  tag: v1.23.1
- repository: k8scloudprovider/barbican-kms-plugin
  tag: v1.23.0
- repository: k8scloudprovider/cinder-csi-plugin
  tag: v1.23.0
- repository: k8scloudprovider/k8s-keystone-auth
  tag: v1.23.0
- repository: k8scloudprovider/magnum-auto-healer
  tag: v1.23.0
- repository: k8scloudprovider/manila-csi-plugin
  tag: v1.23.0
- repository: k8scloudprovider/octavia-ingress-controller
  tag: v1.23.0

# k8s-sidecar
- repository: kiwigrid/k8s-sidecar
  host: quay.io
  tag: 1.15.6

# metrics-server
- repository: metrics-server/metrics-server
  host: k8s.gcr.io
  tag: v0.5.2

# openstackmagnum/cluster-autoscaler
- repository: openstackmagnum/cluster-autoscaler
  tag: v1.22.0
- repository: openstackmagnum/cluster-autoscaler
  tag: v1.23.0

# Prometheus
- repository: prometheus/alertmanager
  host: quay.io
  tag: v0.23.0
- repository: prometheus/prometheus
  host: quay.io
  tag: v2.33.4
- repository: prometheus-adapter/prometheus-adapter
  host: k8s.gcr.io
  tag: v0.9.1
- repository: prometheus-operator/prometheus-operator
  host: quay.io
  tag: v0.54.1

# Rancher Hyperkube
- repository: rancher/hyperkube
  tag: v1.21.9-rancher1
  target_tag: v1.21.9 
- repository: rancher/hyperkube
  tag: v1.22.6-rancher1
  target_tag: v1.22.6
- repository: rancher/hyperkube
  tag: v1.23.4-rancher1
  target_tag: v1.23.4

# Thanos
- repository: thanos/thanos
  host: quay.io
  tag: v0.24.0

# K8S SIG Storage/Cinder CSI
- repository: sig-storage/livenessprobe
  host: k8s.gcr.io
  tag: v2.5.0
- repository: sig-storage/csi-node-driver-registrar
  host: k8s.gcr.io
  tag: v2.4.0
- repository: sig-storage/csi-snapshotter
  host: k8s.gcr.io
  tag: v4.2.1
- repository: sig-storage/csi-resizer
  host: k8s.gcr.io
  tag: v1.3.0
- repository: sig-storage/csi-attacher
  host: k8s.gcr.io
  tag: v3.3.0
