target:
  host: ghcr.io
  repository: stackhpc/calico
  auth:
    username: GHCR_USERNAME
    password: GHCR_PASSWORD
sources:
# v3.25.2
- repository: calico/apiserver
  host: docker.io
  tag: v3.25.2
- repository: calico/cni
  host: docker.io
  tag: v3.25.2
- repository: calico/csi
  host: docker.io
  tag: v3.25.2
- repository: calico/kube-controllers
  host: docker.io
  tag: v3.25.2
- repository: calico/node
  host: docker.io
  tag: v3.25.2
- repository: calico/node-driver-registrar
  host: docker.io
  tag: v3.25.2
- repository: calico/pod2daemon-flexvol
  host: docker.io
  tag: v3.25.2
- repository: calico/typha
  host: docker.io
  tag: v3.25.2
# v3.26.3
- repository: calico/apiserver
  host: docker.io
  tag: v3.26.3
- repository: calico/cni
  host: docker.io
  tag: v3.26.3
- repository: calico/csi
  host: docker.io
  tag: v3.26.3
- repository: calico/kube-controllers
  host: docker.io
  tag: v3.26.3
- repository: calico/node
  host: docker.io
  tag: v3.26.3
- repository: calico/node-driver-registrar
  host: docker.io
  tag: v3.26.3
- repository: calico/pod2daemon-flexvol
  host: docker.io
  tag: v3.26.3
- repository: calico/typha
  host: docker.io
  tag: v3.26.3
# v3.27.0
- repository: calico/apiserver
  host: docker.io
  tag: v3.27.0
- repository: calico/cni
  host: docker.io
  tag: v3.27.0
- repository: calico/csi
  host: docker.io
  tag: v3.27.0
- repository: calico/kube-controllers
  host: docker.io
  tag: v3.27.0
- repository: calico/node
  host: docker.io
  tag: v3.27.0
- repository: calico/node-driver-registrar
  host: docker.io
  tag: v3.27.0
- repository: calico/pod2daemon-flexvol
  host: docker.io
  tag: v3.27.0
- repository: calico/typha
  host: docker.io
  tag: v3.27.0
