name: Sync Container images

on:
  push:
    branches:
      - main

env:
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Prepare Go
         uses: actions/setup-go@v5
         with:
           go-version: '^1.22'

       - name: Checkout sinker
         uses: actions/checkout@master
         with:
           repository: stackhpc/sinker
           ref: refs/heads/stackhpc

       - name: Install sinker
         run: make build && cp ./sinker ../

       - name: Checkout container-image-sync
         uses: actions/checkout@master

       - name: Run sinker pull
         run: ../sinker pull

       - name: Run sinker push (dry-run)
         run: ../sinker push --dryrun

       - name: Run sinker push
         run: ../sinker push
