name: Check sinker config

on:
  pull_request:

env:
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
       - name: Prepare Go
         uses: actions/setup-go@v5
         with:
           go-version: '^1.22'

       - name: Checkout sinker 
         uses: actions/checkout@master
         with:
           repository: stackhpc/sinker
           ref: refs/heads/stackhpc

       - name: Install sinker
         run: make build && cp ./sinker ../

       - name: Checkout container-image-sync
         uses: actions/checkout@master

       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_TOKEN }}

       #- name: Run sinker check
       #  run: ../sinker check

       - name: Run sinker push (dry-run)
         run: ../sinker push --dryrun
