name: Check sinker config

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Fetch history
         run: git fetch --prune --unshallow

       - name: Prepare Go
         uses: actions/setup-go@v2
         with:
           go-version: '^1.17.0'

       - name: Install sinker
         run: go install github.com/plexsystems/sinker@latest

       - name: Check images
         run: sinker check
