name: Check sinker config

on:
  pull_request:

env:
  GHCR_USERNAME: ${{ github.actor }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
       - name: Prepare Go
         uses: actions/setup-go@v2
         with:
           go-version: '^1.17.0'

       - name: Checkout sinker 
         uses: actions/checkout@master
         with:
           repository: mnasiadka/sinker
           ref: refs/heads/target-tag

       - name: Install sinker
         run: make build && cp ./sinker ../

       - name: Checkout container-image-sync
         uses: actions/checkout@master

       - name: Run sinker check
         run: ../sinker check

       - name: Run sinker push (dry-run)
         run: ../sinker push --dryrun
